// // import type { Metadata } from "next";
// // import localFont from "next/font/local";
// // import "./globals.css";

// // const geistSans = localFont({
// //   src: "./fonts/GeistVF.woff",
// //   variable: "--font-geist-sans",
// //   weight: "100 900",
// // });
// // const geistMono = localFont({
// //   src: "./fonts/GeistMonoVF.woff",
// //   variable: "--font-geist-mono",
// //   weight: "100 900",
// // });

// // export const metadata: Metadata = {
// //   title: "Create Next App",
// //   description: "Generated by create next app",
// // };

// // export default function RootLayout({
// //   children,
// // }: Readonly<{
// //   children: React.ReactNode;
// // }>) {
// //   return (
// //     <html lang="en">
// //       <body
// //         className={`${geistSans.variable} ${geistMono.variable} antialiased`}
// //       >
// //         {children}
// //       </body>
// //     </html>
// //   );
// // }


// // app/layout.tsx
// import Link from "next/link"
// import './globals.css'
// import { useState } from "react"

// export default function Layout({ children }: { children: React.ReactNode }) {
//   const [currentPage, setCurrentPage] = useState('home') // ページの状態を管理
//   return (
//     <html lang="en">
//       <body>
//         <header className="header">
//           <nav>
//             <ul className="nav-links">
//               <li><Link href="/">Home</Link></li>
//               <li><Link href="/courses">Courses</Link></li>
//               <li><Link href="/instructors">Instructors</Link></li>
//               <li><Link href="/blog">Blog</Link></li>
//               <li><Link href="/login">Login</Link></li>
//               <li><Link href="/signup">Sign Up</Link></li>
//             </ul>
//           </nav>
//         </header>
//         <main>{children}</main>
//         <footer>© 2024 Your Company</footer>
//       </body>
//     </html>
//   )
// }


// app/layout.tsx

// app/layout.tsx

import type { Metadata } from "next";
import localFont from "next/font/local";
// import Link from "next/link";
import "./globals.css";

// フォント設定
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});

// メタデータ
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

// レイアウトコンポーネント
export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ja">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        {/* <header className="header">
          <nav>
            <ul className="nav-links">
              <li><Link href="/">Home</Link></li>
              <li><Link href="/courses">Courses</Link></li>
              <li><Link href="/instructors">Instructors</Link></li>
              <li><Link href="/blog">Blog</Link></li>
              <li><Link href="/login">Login</Link></li>
              <li><Link href="/signup">Sign Up</Link></li>
            </ul>
          </nav>
        </header> */}
        <main>{children}</main>
        <footer>© 2024 Your Company</footer>
      </body>
    </html>
  );
}
